# config/packages/lexik_jwt_authentication.yaml
lexik_jwt_authentication:
    secret_key:       '%env(resolve:JWT_PRIVATE_KEY)%'
    public_key:       '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase:      '%env(JWT_PASSPHRASE)%'
    token_ttl:        3600 # Dur√©e de vie du token en secondes (1 heure)
